extends: default

rules:
  line-length:
    max: 200
    level: warning   # не валим билд из-за длины строк
  document-start: disable
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  comments:
    min-spaces-from-content: 1
  trailing-spaces: enable
