name: ci

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r rio/requirements.txt

      - name: Lint YAML (non-blocking)
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
        continue-on-error: true

      - name: Run tests (non-blocking)
        run: |
          if [ -f "pytest.ini" ] || ls tests 1>/dev/null 2>&1; then
            pytest
          else
            echo "No tests yet – skipping"
          fi
