name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install yamllint

      - name: Lint YAML (repo-wide)
        run: |
          if [ -f ".yamllint.yml" ]; then
            yamllint -c .yamllint.yml . || true
          else
            echo "No .yamllint.yml found, skipping"
          fi

      - name: Install project requirements (optional)
        run: |
          if [ -f "rio/requirements.txt" ]; then
            pip install -r rio/requirements.txt || true
          fi
          if [ -d "tests" ] || [ -f "pytest.ini" ]; then
            pip install pytest || true
          fi

      - name: Python sanity
        run: python -c "print('python ok')"

      - name: Run tests (skip if none)
        run: |
          if [ -d "tests" ] || [ -f 'pytest.ini' ]; then
            pytest || true
          else
            echo "No tests found – skipping"
          fi
