name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML (repo-wide)
        run: |
          if [ -f ".yamllint.yml" ] || [ -f ".yamllint.yaml" ] || [ -f ".yamllint" ]; then
            yamllint . || true
          else
            cat > .yamllint.yml <<'YML'
            extends: default
            rules:
              line-length:
                max: 200
                level: warning
              document-start: disable
              truthy:
                allowed-values: ["true", "false"]
                check-keys: false
              comments:
                min-spaces-from-content: 1
              trailing-spaces: enable
            YML
            yamllint -c .yamllint.yml . || true
          fi

      - name: Install project requirements (optional)
        run: |
          if [ -f "rio/requirements.txt" ]; then
            pip install -r rio/requirements.txt || true
          fi
          if [ -d "tests" ] || [ -f "pytest.ini" ]; then
            pip install pytest || true
          fi

      - name: Python sanity
        run: |
          python - <<'PY'
          print("python ok")
          PY

      - name: Run tests (skip if none)
        run: |
          if [ -d "tests" ] || [ -f "pytest.ini" ]; then
            pytest || true
          else
            echo "No tests found – skipping"
          fi
